CREATE TABLE Genre (
        id INT GENERATED BY DEFAULT AS IDENTITY ,
        name VARCHAR(100) NOT NULL,
        PRIMARY KEY (id)
);

CREATE TABLE Platform (
        id INT GENERATED BY DEFAULT AS IDENTITY,
        name VARCHAR(100) NOT NULL,
        image_path VARCHAR(255)
);

CREATE TABLE Game (
        id INT GENERATED BY DEFAULT AS IDENTITY ,
        title VARCHAR(255) NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        image_path VARCHAR(255),
        reviews_count INT DEFAULT 0,
        discount DECIMAL(5, 2) DEFAULT 0.00,
        number_of_stars INT,
        description VARCHAR2(4000),
        PRIMARY KEY (id)
);

CREATE TABLE Game_Genre (
        game_id INT,
        genre_id INT,
        PRIMARY KEY (game_id, genre_id),
        FOREIGN KEY (game_id) REFERENCES Game(id) ON DELETE CASCADE,
        FOREIGN KEY (genre_id) REFERENCES Genre(id) ON DELETE CASCADE
);

CREATE TABLE Game_Platform (
        game_id INT,
        platform_id INT,
        PRIMARY KEY (game_id, platform_id),
        FOREIGN KEY (game_id) REFERENCES Game(id) ON DELETE CASCADE,
        FOREIGN KEY (platform_id) REFERENCES Platform(id) ON DELETE CASCADE
);
